### ISSUE TITLE
How to add more than one folder to query?

### ISSUE THREAD

**Issue by cordovero** [erazlogo/obsidian-lit-notes-search#1]
Hello,
I really love your search tool, thank you so much for all the work you're making available! 
I was wondering how I would edit the view.js file to query from more than my literature notes folder? I don't know javascript at all and any attempts I make to add a second folder to search ends in parsing errors...
Thank you so much!

**Comment by erazlogo** [comment]
Change `dv.pages('"your-literature-notes-folder"')` to:

`dv.pages('"path1" or "path2"')`

**Comment by cordovero** [comment]
Thank you so much!
